
export interface Provider {
  name: string;
  staffingPercentage: number;
  projectPercentage: number;
  softwarePercentage: number;
  accountCode: string;
}

export interface ProviderCategory {
  code: string;
  name: string;
  providers: Provider[];
}

export const providerData: ProviderCategory[] = [
  {
    code: '701001',
    name: '701001 - Alquileres y Depósitos',
    providers: [
      { name: 'BALBOA STORAGE', staffingPercentage: 0, projectPercentage: 100, softwarePercentage: 0, accountCode: '701001' },
      { name: 'SAKETINI', staffingPercentage: 0, projectPercentage: 100, softwarePercentage: 0, accountCode: '701001' },
    ],
  },
  {
    code: '701003',
    name: '701003 - Telecomunicaciones',
    providers: [
      { name: 'CABLE & WIRELESS', staffingPercentage: 0, projectPercentage: 100, softwarePercentage: 0, accountCode: '701003' },
      { name: 'OVNICOM', staffingPercentage: 0, projectPercentage: 100, softwarePercentage: 0, accountCode: '701003' },
    ],
  },
  {
    code: '701006',
    name: '701006 - Gastos Generales y Representación',
    providers: [
      { name: 'AGUSTIN RUIZ', staffingPercentage: 0, projectPercentage: 100, softwarePercentage: 0, accountCode: '701006' },
      { name: 'ASAP', staffingPercentage: 0, projectPercentage: 100, softwarePercentage: 0, accountCode: '701006' },
      { name: 'ASSETS TRUST & CORPORATE', staffingPercentage: 0, projectPercentage: 100, softwarePercentage: 0, accountCode: '701006' },
      { name: 'B&D TRAP', staffingPercentage: 0, projectPercentage: 100, softwarePercentage: 0, accountCode: '701006' },
      { name: 'BELISA BECERRA', staffingPercentage: 0, projectPercentage: 100, softwarePercentage: 0, accountCode: '701006' },
      { name: 'BLUE MOON', staffingPercentage: 0, projectPercentage: 100, softwarePercentage: 0, accountCode: '701006' },
      { name: 'BUBBA GUMP', staffingPercentage: 0, projectPercentage: 100, softwarePercentage: 0, accountCode: '701006' },
      { name: 'BUCO POLLO', staffingPercentage: 0, projectPercentage: 100, softwarePercentage: 0, accountCode: '701006' },
      { name: 'CARIBBEAN FRANCHISE', staffingPercentage: 0, projectPercentage: 100, softwarePercentage: 0, accountCode: '701006' },
      { name: 'CEVICHE INKA', staffingPercentage: 0, projectPercentage: 100, softwarePercentage: 0, accountCode: '701006' },
      { name: 'CHIPOTLE MEXICAN GRILL', staffingPercentage: 0, projectPercentage: 100, softwarePercentage: 0, accountCode: '701006' },
      { name: 'CIAO BELLA', staffingPercentage: 0, projectPercentage: 100, softwarePercentage: 0, accountCode: '701006' },
      { name: 'COPA AIR', staffingPercentage: 0, projectPercentage: 100, softwarePercentage: 0, accountCode: '701006' },
      { name: 'DEEL', staffingPercentage: 0, projectPercentage: 100, softwarePercentage: 0, accountCode: '701006' },
      { name: 'DILIDO BEACH CLUB', staffingPercentage: 0, projectPercentage: 100, softwarePercentage: 0, accountCode: '701006' },
      { name: 'LA RANA DORADA', staffingPercentage: 0, projectPercentage: 100, softwarePercentage: 0, accountCode: '701006' },
      { name: 'MIAMI INTERNATIONAL AIRPORT', staffingPercentage: 0, projectPercentage: 100, softwarePercentage: 0, accountCode: '701006' },
      { name: 'NOVEY', staffingPercentage: 0, projectPercentage: 100, softwarePercentage: 0, accountCode: '701006' },
      { name: 'PEDIDOS YA', staffingPercentage: 0, projectPercentage: 100, softwarePercentage: 0, accountCode: '701006' },
      { name: 'PERU CHICKEN', staffingPercentage: 0, projectPercentage: 100, softwarePercentage: 0, accountCode: '701006' },
      { name: 'POLLO TROPICAL', staffingPercentage: 0, projectPercentage: 100, softwarePercentage: 0, accountCode: '701006' },
      { name: 'PORTEX', staffingPercentage: 0, projectPercentage: 100, softwarePercentage: 0, accountCode: '701006' },
      { name: 'RENT SMART CAR RENTAL', staffingPercentage: 0, projectPercentage: 100, softwarePercentage: 0, accountCode: '701006' },
      { name: 'RESTAURANTE LE BISTROT', staffingPercentage: 0, projectPercentage: 100, softwarePercentage: 0, accountCode: '701006' },
      { name: 'SLABON', staffingPercentage: 0, projectPercentage: 100, softwarePercentage: 0, accountCode: '701006' },
      { name: 'STARBUCKS', staffingPercentage: 0, projectPercentage: 100, softwarePercentage: 0, accountCode: '701006' },
      { name: 'TALAYOTES', staffingPercentage: 0, projectPercentage: 100, softwarePercentage: 0, accountCode: '701006' },
      { name: 'TGI FRIDAYS', staffingPercentage: 0, projectPercentage: 100, softwarePercentage: 0, accountCode: '701006' },
      { name: 'UBER', staffingPercentage: 0, projectPercentage: 100, softwarePercentage: 0, accountCode: '701006' },
      { name: 'OCEAN PARKING', staffingPercentage: 0, projectPercentage: 100, softwarePercentage: 0, accountCode: '701006' },
    ],
  },
  {
    code: '701008',
    name: '701008 - Suministros y Servicios Varios',
    providers: [
      { name: 'CONTROL TECK', staffingPercentage: 0, projectPercentage: 100, softwarePercentage: 0, accountCode: '701008' },
      { name: 'COPY COLOR', staffingPercentage: 0, projectPercentage: 100, softwarePercentage: 0, accountCode: '701008' },
      { name: 'DAVE NORLAND AUSTIN CAMPOS', staffingPercentage: 0, projectPercentage: 100, softwarePercentage: 0, accountCode: '701008' },
      { name: 'GEOVANI GONZALEZ', staffingPercentage: 0, projectPercentage: 100, softwarePercentage: 0, accountCode: '701008' },
      { name: 'PRICESMART', staffingPercentage: 0, projectPercentage: 100, softwarePercentage: 0, accountCode: '701008' },
      { name: 'STRAUSS WATER', staffingPercentage: 0, projectPercentage: 100, softwarePercentage: 0, accountCode: '701008' },
      { name: 'SUPER 99', staffingPercentage: 0, projectPercentage: 100, softwarePercentage: 0, accountCode: '701008' },
      { name: 'VISIONARTE', staffingPercentage: 0, projectPercentage: 100, softwarePercentage: 0, accountCode: '701008' },
    ],
  },
  {
    code: '701009',
    name: '701009 - Educación y Capacitación',
    providers: [
      { name: 'MICROSOFT', staffingPercentage: 0, projectPercentage: 0, softwarePercentage: 100, accountCode: '701009' },
      { name: 'PANAMERICAN UNIVERSY', staffingPercentage: 0, projectPercentage: 100, softwarePercentage: 0, accountCode: '701009' },
    ],
  },
  {
    code: '701011',
    name: '701011 - Servicios Contables y Fiscales',
    providers: [
      { name: 'FCG', staffingPercentage: 0, projectPercentage: 100, softwarePercentage: 0, accountCode: '701011' },
    ],
  },
  {
    code: '701019',
    name: '701019 - Limpieza y Mantenimiento',
    providers: [
      { name: 'BROOMDAY', staffingPercentage: 0, projectPercentage: 100, softwarePercentage: 0, accountCode: '701019' },
    ],
  },
  {
    code: '701020',
    name: '701020 - Servicios Públicos',
    providers: [
      { name: 'NATURGY', staffingPercentage: 0, projectPercentage: 100, softwarePercentage: 0, accountCode: '701020' },
    ],
  },
  {
    code: '701501',
    name: '701501 - Servicios Profesionales',
    providers: [
      { name: 'ALEIKA DE LEON', staffingPercentage: 0, projectPercentage: 100, softwarePercentage: 0, accountCode: '701501' },
      { name: 'ALEJANDRO HERAZO', staffingPercentage: 0, projectPercentage: 100, softwarePercentage: 0, accountCode: '701501' },
      { name: 'ANDRES ORLANDO CORTES', staffingPercentage: 0, projectPercentage: 100, softwarePercentage: 0, accountCode: '701501' },
      { name: 'CESAR BOLAÑOS', staffingPercentage: 0, projectPercentage: 100, softwarePercentage: 0, accountCode: '701501' },
      { name: 'DAVID REYES', staffingPercentage: 0, projectPercentage: 100, softwarePercentage: 0, accountCode: '701501' },
      { name: 'DIANA PAIVA', staffingPercentage: 0, projectPercentage: 100, softwarePercentage: 0, accountCode: '701501' },
      { name: 'ELSY ZAPATA', staffingPercentage: 0, projectPercentage: 100, softwarePercentage: 0, accountCode: '701501' },
      { name: 'FIVER', staffingPercentage: 0, projectPercentage: 100, softwarePercentage: 0, accountCode: '701501' },
      { name: 'JAY WADHWANI', staffingPercentage: 0, projectPercentage: 100, softwarePercentage: 0, accountCode: '701501' },
      { name: 'JUAN PINZON', staffingPercentage: 0, projectPercentage: 100, softwarePercentage: 0, accountCode: '701501' },
      { name: 'LENIN VINICIO RIOS', staffingPercentage: 0, projectPercentage: 100, softwarePercentage: 0, accountCode: '701501' },
      { name: 'MIGUEL RODRIGUEZ', staffingPercentage: 0, projectPercentage: 100, softwarePercentage: 0, accountCode: '701501' },
      { name: 'RODOLFO REIMER', staffingPercentage: 0, projectPercentage: 100, softwarePercentage: 0, accountCode: '701501' },
    ],
  },
  {
    code: '702001',
    name: '702001 - Personal/Nómina',
    providers: [
      { name: 'Alberto Javier Espinoza Ortega', staffingPercentage: 100, projectPercentage: 0, softwarePercentage: 0, accountCode: '702001' },
      { name: 'Alexander Alvarez', staffingPercentage: 100, projectPercentage: 0, softwarePercentage: 0, accountCode: '702001' },
      { name: 'Alexs Aburto', staffingPercentage: 100, projectPercentage: 0, softwarePercentage: 0, accountCode: '702001' },
      { name: 'Alfredo Illanes', staffingPercentage: 100, projectPercentage: 0, softwarePercentage: 0, accountCode: '702001' },
      { name: 'Alfredo Sanoja', staffingPercentage: 100, projectPercentage: 0, softwarePercentage: 0, accountCode: '702001' },
      { name: 'Angie Nayelly Rueda', staffingPercentage: 100, projectPercentage: 0, softwarePercentage: 0, accountCode: '702001' },
      { name: 'Argel Alfaro', staffingPercentage: 100, projectPercentage: 0, softwarePercentage: 0, accountCode: '702001' },
      { name: 'CARLOS CORTES', staffingPercentage: 100, projectPercentage: 0, softwarePercentage: 0, accountCode: '702001' },
      { name: 'CARLOS PADILLA', staffingPercentage: 100, projectPercentage: 0, softwarePercentage: 0, accountCode: '702001' },
      { name: 'Cristopher Chavez', staffingPercentage: 100, projectPercentage: 0, softwarePercentage: 0, accountCode: '702001' },
      { name: 'DIEGO MELENDEZ', staffingPercentage: 100, projectPercentage: 0, softwarePercentage: 0, accountCode: '702001' },
      { name: 'Daniel Rocha', staffingPercentage: 100, projectPercentage: 0, softwarePercentage: 0, accountCode: '702001' },
      { name: 'Diana Alexandra Davila', staffingPercentage: 100, projectPercentage: 0, softwarePercentage: 0, accountCode: '702001' },
      { name: 'Diego Ramirez', staffingPercentage: 100, projectPercentage: 0, softwarePercentage: 0, accountCode: '702001' },
      { name: 'EDUAR VARGAS', staffingPercentage: 100, projectPercentage: 0, softwarePercentage: 0, accountCode: '702001' },
      { name: 'Edison Lopez', staffingPercentage: 100, projectPercentage: 0, softwarePercentage: 0, accountCode: '702001' },
      { name: 'Fabián Cabañas', staffingPercentage: 100, projectPercentage: 0, softwarePercentage: 0, accountCode: '702001' },
      { name: 'Freddy Uzcategui', staffingPercentage: 100, projectPercentage: 0, softwarePercentage: 0, accountCode: '702001' },
      { name: 'Geovani Vuelvas', staffingPercentage: 100, projectPercentage: 0, softwarePercentage: 0, accountCode: '702001' },
      { name: 'Guillermo Corredor Soto', staffingPercentage: 100, projectPercentage: 0, softwarePercentage: 0, accountCode: '702001' },
      { name: 'HEVERT GELIS', staffingPercentage: 100, projectPercentage: 0, softwarePercentage: 0, accountCode: '702001' },
      { name: 'Hanson Restrepo', staffingPercentage: 100, projectPercentage: 0, softwarePercentage: 0, accountCode: '702001' },
      { name: 'Heidy Colorado', staffingPercentage: 100, projectPercentage: 0, softwarePercentage: 0, accountCode: '702001' },
      { name: 'JOSE OCHOA', staffingPercentage: 100, projectPercentage: 0, softwarePercentage: 0, accountCode: '702001' },
      { name: 'Joan Pulgarin', staffingPercentage: 100, projectPercentage: 0, softwarePercentage: 0, accountCode: '702001' },
      { name: 'Joel Palma', staffingPercentage: 100, projectPercentage: 0, softwarePercentage: 0, accountCode: '702001' },
      { name: 'Johnny Antonio Arcia Rivera', staffingPercentage: 100, projectPercentage: 0, softwarePercentage: 0, accountCode: '702001' },
      { name: 'Jorge Jimenez', staffingPercentage: 100, projectPercentage: 0, softwarePercentage: 0, accountCode: '702001' },
      { name: 'Jose Carlos Villalba Paredes', staffingPercentage: 100, projectPercentage: 0, softwarePercentage: 0, accountCode: '702001' },
      { name: 'Jose Luis Perez', staffingPercentage: 100, projectPercentage: 0, softwarePercentage: 0, accountCode: '702001' },
      { name: 'Jose Romero', staffingPercentage: 100, projectPercentage: 0, softwarePercentage: 0, accountCode: '702001' },
      { name: 'Juan Echeverry', staffingPercentage: 100, projectPercentage: 0, softwarePercentage: 0, accountCode: '702001' },
      { name: 'Julio Aburto', staffingPercentage: 100, projectPercentage: 0, softwarePercentage: 0, accountCode: '702001' },
      { name: 'Julio Gonzalez', staffingPercentage: 100, projectPercentage: 0, softwarePercentage: 0, accountCode: '702001' },
      { name: 'Karen Gonzales', staffingPercentage: 100, projectPercentage: 0, softwarePercentage: 0, accountCode: '702001' },
      { name: 'Katherine Yaoska Perez Gonzalez', staffingPercentage: 100, projectPercentage: 0, softwarePercentage: 0, accountCode: '702001' },
      { name: 'Kennett Ariel Herrera', staffingPercentage: 100, projectPercentage: 0, softwarePercentage: 0, accountCode: '702001' },
      { name: 'Kevin Vanegas', staffingPercentage: 100, projectPercentage: 0, softwarePercentage: 0, accountCode: '702001' },
      { name: 'Kevin Yamil Garcia', staffingPercentage: 100, projectPercentage: 0, softwarePercentage: 0, accountCode: '702001' },
      { name: 'LAURA LEYTON', staffingPercentage: 100, projectPercentage: 0, softwarePercentage: 0, accountCode: '702001' },
      { name: 'Luciano Vega', staffingPercentage: 100, projectPercentage: 0, softwarePercentage: 0, accountCode: '702001' },
      { name: 'Ludwin Mejia', staffingPercentage: 100, projectPercentage: 0, softwarePercentage: 0, accountCode: '702001' },
      { name: 'MICHAEL ROMERO', staffingPercentage: 100, projectPercentage: 0, softwarePercentage: 0, accountCode: '702001' },
      { name: 'Manuela Cardona', staffingPercentage: 100, projectPercentage: 0, softwarePercentage: 0, accountCode: '702001' },
      { name: 'Maria Alejandra Gomez', staffingPercentage: 100, projectPercentage: 0, softwarePercentage: 0, accountCode: '702001' },
      { name: 'Maria Jose Montes', staffingPercentage: 100, projectPercentage: 0, softwarePercentage: 0, accountCode: '702001' },
      { name: 'Maria Veronica Luna', staffingPercentage: 100, projectPercentage: 0, softwarePercentage: 0, accountCode: '702001' },
      { name: 'Maria mendoza', staffingPercentage: 100, projectPercentage: 0, softwarePercentage: 0, accountCode: '702001' },
      { name: 'Marvin Antonio Arguello Aguirre', staffingPercentage: 100, projectPercentage: 0, softwarePercentage: 0, accountCode: '702001' },
      { name: 'Miguel Aurela Alvarez', staffingPercentage: 100, projectPercentage: 0, softwarePercentage: 0, accountCode: '702001' },
      { name: 'Miguel Marinez', staffingPercentage: 100, projectPercentage: 0, softwarePercentage: 0, accountCode: '702001' },
      { name: 'NOHELIA RIVERA', staffingPercentage: 100, projectPercentage: 0, softwarePercentage: 0, accountCode: '702001' },
      { name: 'Nahum Casco', staffingPercentage: 100, projectPercentage: 0, softwarePercentage: 0, accountCode: '702001' },
      { name: 'Onam Diaz', staffingPercentage: 100, projectPercentage: 0, softwarePercentage: 0, accountCode: '702001' },
      { name: 'Oscar España', staffingPercentage: 100, projectPercentage: 0, softwarePercentage: 0, accountCode: '702001' },
      { name: 'ROBERT SANTIAGO NOVOA', staffingPercentage: 100, projectPercentage: 0, softwarePercentage: 0, accountCode: '702001' },
      { name: 'Ramon Salvador Pereira', staffingPercentage: 100, projectPercentage: 0, softwarePercentage: 0, accountCode: '702001' },
      { name: 'Rommel Mojica', staffingPercentage: 100, projectPercentage: 0, softwarePercentage: 0, accountCode: '702001' },
      { name: 'Samuel Barberena', staffingPercentage: 100, projectPercentage: 0, softwarePercentage: 0, accountCode: '702001' },
      { name: 'Santiago Osorno', staffingPercentage: 100, projectPercentage: 0, softwarePercentage: 0, accountCode: '702001' },
      { name: 'Santiago Sepulveda', staffingPercentage: 100, projectPercentage: 0, softwarePercentage: 0, accountCode: '702001' },
      { name: 'Santiago Velez', staffingPercentage: 100, projectPercentage: 0, softwarePercentage: 0, accountCode: '702001' },
      { name: 'Scarleth Massiel Suárez Lara', staffingPercentage: 100, projectPercentage: 0, softwarePercentage: 0, accountCode: '702001' },
      { name: 'Sebastian Ferney Castro Olmos', staffingPercentage: 100, projectPercentage: 0, softwarePercentage: 0, accountCode: '702001' },
      { name: 'Simon Peña', staffingPercentage: 100, projectPercentage: 0, softwarePercentage: 0, accountCode: '702001' },
      { name: 'Wendy Mejia', staffingPercentage: 100, projectPercentage: 0, softwarePercentage: 0, accountCode: '702001' },
      { name: 'William Andres Garcia', staffingPercentage: 100, projectPercentage: 0, softwarePercentage: 0, accountCode: '702001' },
      { name: 'Wilmer Leonel Brandt Reyes', staffingPercentage: 100, projectPercentage: 0, softwarePercentage: 0, accountCode: '702001' },
      { name: 'Yamil Arroliga', staffingPercentage: 100, projectPercentage: 0, softwarePercentage: 0, accountCode: '702001' },
      { name: 'Yelibel Monrroy', staffingPercentage: 100, projectPercentage: 0, softwarePercentage: 0, accountCode: '702001' },
      { name: 'Yubeli Martinez', staffingPercentage: 100, projectPercentage: 0, softwarePercentage: 0, accountCode: '702001' },
      { name: 'Zulemay Pescod', staffingPercentage: 100, projectPercentage: 0, softwarePercentage: 0, accountCode: '702001' },
    ],
  },
  {
    code: '703020',
    name: '703020 - Seguros y Beneficios',
    providers: [
      { name: 'PAN AMERICAN LIFE', staffingPercentage: 100, projectPercentage: 0, softwarePercentage: 0, accountCode: '703020' },
      { name: 'PETROLEOS DELTA', staffingPercentage: 100, projectPercentage: 0, softwarePercentage: 0, accountCode: '703020' },
      { name: 'POWER CLUB', staffingPercentage: 100, projectPercentage: 0, softwarePercentage: 0, accountCode: '703020' },
      { name: 'VALE GENERAL', staffingPercentage: 100, projectPercentage: 0, softwarePercentage: 0, accountCode: '703020' },
    ],
  },
  {
    code: '707003',
    name: '707003 - Software y Servicios Digitales',
    providers: [
      { name: '7PACE', staffingPercentage: 0, projectPercentage: 0, softwarePercentage: 100, accountCode: '707003' },
      { name: 'ABACUS.AI', staffingPercentage: 0, projectPercentage: 0, softwarePercentage: 100, accountCode: '707003' },
      { name: 'ACTUAL REPORT', staffingPercentage: 0, projectPercentage: 0, softwarePercentage: 100, accountCode: '707003' },
      { name: 'ADOBE', staffingPercentage: 0, projectPercentage: 0, softwarePercentage: 100, accountCode: '707003' },
      { name: 'ANTHROPIC', staffingPercentage: 0, projectPercentage: 0, softwarePercentage: 100, accountCode: '707003' },
      { name: 'APPFIGURES', staffingPercentage: 0, projectPercentage: 0, softwarePercentage: 100, accountCode: '707003' },
      { name: 'CODE TWO', staffingPercentage: 0, projectPercentage: 0, softwarePercentage: 100, accountCode: '707003' },
      { name: 'COMPUTACION MONRENCA', staffingPercentage: 0, projectPercentage: 0, softwarePercentage: 100, accountCode: '707003' },
      { name: 'FACEBOOK', staffingPercentage: 0, projectPercentage: 0, softwarePercentage: 100, accountCode: '707003' },
      { name: 'FREEPIK', staffingPercentage: 0, projectPercentage: 0, softwarePercentage: 100, accountCode: '707003' },
      { name: 'GITHUB', staffingPercentage: 0, projectPercentage: 0, softwarePercentage: 100, accountCode: '707003' },
      { name: 'GODADDY', staffingPercentage: 0, projectPercentage: 0, softwarePercentage: 100, accountCode: '707003' },
      { name: 'H & CO GLOBAL', staffingPercentage: 0, projectPercentage: 0, softwarePercentage: 100, accountCode: '707003' },
      { name: 'HUMANSMART CONSULTING', staffingPercentage: 0, projectPercentage: 0, softwarePercentage: 100, accountCode: '707003' },
      { name: 'INGRAM', staffingPercentage: 0, projectPercentage: 0, softwarePercentage: 100, accountCode: '707003' },
      { name: 'JIBBLE', staffingPercentage: 0, projectPercentage: 0, softwarePercentage: 100, accountCode: '707003' },
      { name: 'LAMBDATEST', staffingPercentage: 0, projectPercentage: 0, softwarePercentage: 100, accountCode: '707003' },
      { name: 'LICENCIAS ONLINE', staffingPercentage: 0, projectPercentage: 0, softwarePercentage: 100, accountCode: '707003' },
      { name: 'LINKEDIN', staffingPercentage: 0, projectPercentage: 0, softwarePercentage: 100, accountCode: '707003' },
      { name: 'MICROSOFT AZURE', staffingPercentage: 0, projectPercentage: 0, softwarePercentage: 100, accountCode: '707003' },
      { name: 'MONGO DB', staffingPercentage: 0, projectPercentage: 0, softwarePercentage: 100, accountCode: '707003' },
      { name: 'NORDVPN', staffingPercentage: 0, projectPercentage: 0, softwarePercentage: 100, accountCode: '707003' },
      { name: 'NOTION', staffingPercentage: 0, projectPercentage: 0, softwarePercentage: 100, accountCode: '707003' },
      { name: 'OPEN AI', staffingPercentage: 0, projectPercentage: 0, softwarePercentage: 100, accountCode: '707003' },
      { name: 'PENTESTTOOLS', staffingPercentage: 0, projectPercentage: 0, softwarePercentage: 100, accountCode: '707003' },
      { name: 'POSTMAN', staffingPercentage: 0, projectPercentage: 0, softwarePercentage: 100, accountCode: '707003' },
      { name: 'SENGRID', staffingPercentage: 0, projectPercentage: 0, softwarePercentage: 100, accountCode: '707003' },
      { name: 'SLACK', staffingPercentage: 0, projectPercentage: 0, softwarePercentage: 100, accountCode: '707003' },
      { name: 'TEAMTAILOR', staffingPercentage: 0, projectPercentage: 0, softwarePercentage: 100, accountCode: '707003' },
      { name: 'WEBFLOW', staffingPercentage: 0, projectPercentage: 0, softwarePercentage: 100, accountCode: '707003' },
      { name: 'ZENLEADS INC (APOLLO.IO)', staffingPercentage: 0, projectPercentage: 0, softwarePercentage: 100, accountCode: '707003' },
    ],
  },
  {
    code: '712004',
    name: '712004 - Otros Servicios Tecnológicos',
    providers: [
      { name: 'ODOO TECHNOLOGIES', staffingPercentage: 0, projectPercentage: 0, softwarePercentage: 100, accountCode: '712004' },
      { name: 'SAAS HOLIC', staffingPercentage: 0, projectPercentage: 0, softwarePercentage: 100, accountCode: '712004' },
    ],
  },
];

export const allProviders = providerData.flatMap(category => category.providers);
